import type { PositionConfig } from './types.ts'

export const overallConfig: PositionConfig = {
  key: 'overall',
  emoji: '🌎',
  name: 'Overall Análise',
  rawColumns: [
    'Inf', 'Nação', 'Jogador', 'Idade', 'Clube', 'Altura', 'Pé Preferido',
    'Valor Estimado', 'Salário', 'Expira', 'Minutos', 'Presenças', 'HdJ',
    'Golos', 'Assist.', 'Golos DS', 'OCG', 'Poss Con/90', 'Poss Perd/90',
    'xG', 'xA', 'Faltas Cometidas', 'Faltas Contra', 'Pas A', 'Ps C',
    'Passes Ch', 'PeP', 'Fnt', 'Remates', 'Rem %', 'Cab A', 'Cabs',
    'Press. tent.', 'Press. conc.', 'T Desa', 'Des C', 'Crt',
    'CT-JA', 'CC-JA', 'Cr T', 'Cr C',
    'Golos marcados de fora da área', 'Remates de fora da área em cada 90 minutes',
    'Remates em livres', 'Fj', 'Blq', 'Rems Bloq', 'Alívios', 'Crt D',
    'Amr', 'Cartões vermelhos', 'EPG', 'Sprints/90',
    'Pens', 'Pens M', 'Distância', 'Classificação',
  ],
  identityColumns: {
    Jogador: 'Jogador', Nação: 'Nação', Clube: 'Clube', Idade: 'Idade',
    Salário: 'Salário', Valor: 'Valor Estimado',
  },
  defaultTableColumns: [
    'jogosCompletos', 'gols90', 'ast90', 'npxG90', 'xA90',
    'pctFinNoGol', 'desG90', 'pctCabs', 'pctPassesCertos',
    'pressaoG90', 'dist90', 'notaMedia',
  ],
  metrics: [
    // ── GENERAL ──
    { key: 'jogosCompletos', label: 'Jogos Completos', category: 'general', format: 'number', decimals: 1, displayInTable: true, lowerIsBetter: false,
      formula: (_r, ctx) => ctx.j90 },
    { key: 'jogosTotais', label: 'Jogos Totais', category: 'general', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Presenças']) },
    { key: 'minPartida', label: 'Min/Partida', category: 'general', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Minutos']), ctx.pf(r['Presenças'])) },
    { key: 'jogosComoTitular', label: 'Jogos como Titular', category: 'general', format: 'number', decimals: 1, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => {
        const minPart = ctx.sDiv(ctx.pf(r['Minutos']), ctx.pf(r['Presenças']))
        return minPart >= 60 ? ctx.pf(r['Presenças']) : ctx.pf(r['Presenças']) * ctx.sDiv(minPart, 90)
      } },
    { key: 'hdj', label: 'Man of the Match', category: 'general', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['HdJ']) },
    { key: 'minHdj', label: 'Min/HdJ', category: 'general', format: 'number', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Minutos']), ctx.pf(r['HdJ'])) },
    { key: 'pctHdj', label: '% HdJ', category: 'general', format: 'percentage', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['HdJ']), ctx.j90) },

    // ── ATTACKING ──
    { key: 'gols', label: 'Gols', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Golos']) },
    { key: 'assist', label: 'Assistências', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Assist.']) },
    { key: 'golsAst', label: 'Gols + Ast', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Golos']) + ctx.pf(r['Assist.']) },
    { key: 'gols90', label: 'Gols/90', category: 'attacking', format: 'number', decimals: 2, displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Golos']), ctx.j90) },
    { key: 'ast90', label: 'Ast/90', category: 'attacking', format: 'number', decimals: 2, displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Assist.']), ctx.j90) },
    { key: 'golsAst90', label: 'G+A/90', category: 'attacking', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Golos']) + ctx.pf(r['Assist.']), ctx.j90) },

    // ── xG / xA ──
    { key: 'xG', label: 'xG', category: 'shooting', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['xG']) },
    { key: 'npxG', label: 'npxG', category: 'shooting', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['xG']) - ctx.pf(r['Pens']) * 0.79 },
    { key: 'npxG90', label: 'npxG/90', category: 'shooting', format: 'number', decimals: 2, displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['xG']) - ctx.pf(r['Pens']) * 0.79, ctx.j90) },
    { key: 'xA', label: 'xA', category: 'creation', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['xA']) },
    { key: 'xA90', label: 'xA/90', category: 'creation', format: 'number', decimals: 2, displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['xA']), ctx.j90) },
    { key: 'xGxA', label: 'xG + xA', category: 'shooting', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['xG']) + ctx.pf(r['xA']) },
    { key: 'xGxA90', label: '(xG+xA)/90', category: 'shooting', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['xG']) + ctx.pf(r['xA']), ctx.j90) },

    // ── SHOOTING ──
    { key: 'finalizacoes', label: 'Finalizações', category: 'shooting', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Remates']) },
    { key: 'fin90', label: 'Fin/90', category: 'shooting', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Remates']), ctx.j90) },
    { key: 'finNoGol', label: 'Fin No Gol', category: 'shooting', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Rem %']) },
    { key: 'finNoGol90', label: 'Fin No Gol/90', category: 'shooting', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Rem %']), ctx.j90) },
    { key: 'pctFinNoGol', label: '% Fin No Gol', category: 'shooting', format: 'percentage', displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Rem %']), ctx.pf(r['Remates'])) },
    { key: 'conversaoGols', label: '% Conversão Gols', category: 'shooting', format: 'percentage', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Golos']), ctx.pf(r['Remates'])) },
    { key: 'golsNaoEsperados', label: 'Gols Não Esperados', category: 'shooting', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Golos']) - ctx.pf(r['xG']) },
    { key: 'golsNaoEspSemPen', label: 'Gols NE Sem Pên', category: 'shooting', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => (ctx.pf(r['Golos']) - ctx.pf(r['Pens M'])) - (ctx.pf(r['xG']) - ctx.pf(r['Pens']) * 0.79) },

    // ── CROSSING ──
    { key: 'cruzT', label: 'Cruzamentos Tentados', category: 'creation', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Cr T']) },
    { key: 'cruzC', label: 'Cruzamentos Certos', category: 'creation', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Cr C']) },
    { key: 'pctCruz', label: '% Cruzamentos', category: 'creation', format: 'percentage', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Cr C']), ctx.pf(r['Cr T'])) },

    // ── CREATION ──
    { key: 'passD', label: 'Passes Decisivos', category: 'creation', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Passes Ch']) },
    { key: 'passD90', label: 'Pass D/90', category: 'creation', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Passes Ch']), ctx.j90) },
    { key: 'xAResult', label: 'xA Resultado', category: 'creation', format: 'number', decimals: 2, displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['xA']), ctx.pf(r['Passes Ch'])) },
    { key: 'chancesDespEquipe', label: 'Chances Desp. Equipe', category: 'creation', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['OCG']) },

    // ── SET PIECES ──
    { key: 'tentsBP', label: 'Tentativas Bola Parada', category: 'setpiece', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['CT-JA']) - ctx.pf(r['Cr T']) },
    { key: 'chancesBP', label: 'Chances Bola Parada', category: 'setpiece', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['CC-JA']) - ctx.pf(r['Cr C']) },
    { key: 'pctBP', label: '% Bola Parada', category: 'setpiece', format: 'percentage', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['CC-JA']) - ctx.pf(r['Cr C']), ctx.pf(r['CT-JA']) - ctx.pf(r['Cr T'])) },

    // ── AERIAL ──
    { key: 'cabsDisp', label: 'Cabs Disputados', category: 'aerial', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Cabs']) },
    { key: 'cabsDisp90', label: 'Cabs Disp/90', category: 'aerial', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Cabs']), ctx.j90) },
    { key: 'cabsG', label: 'Cabs Ganhos', category: 'aerial', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Cab A']) },
    { key: 'cabsG90', label: 'Cabs G/90', category: 'aerial', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Cab A']), ctx.j90) },
    { key: 'pctCabs', label: '% Cabs Ganhos', category: 'aerial', format: 'percentage', displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Cab A']), ctx.pf(r['Cabs'])) },

    // ── DEFENDING: TACKLES ──
    { key: 'desT', label: 'Desarmes Tentados', category: 'defending', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['T Desa']) + ctx.pf(r['Faltas Cometidas']) },
    { key: 'desT90', label: 'Des T/90', category: 'defending', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['T Desa']) + ctx.pf(r['Faltas Cometidas']), ctx.j90) },
    { key: 'desG', label: 'Desarmes Ganhos', category: 'defending', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Des C']) },
    { key: 'desG90', label: 'Des G/90', category: 'defending', format: 'number', displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Des C']), ctx.j90) },
    { key: 'pctDes', label: '% Des Ganhos', category: 'defending', format: 'percentage', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Des C']), ctx.pf(r['T Desa']) + ctx.pf(r['Faltas Cometidas'])) },
    { key: 'driblesS', label: 'Dribles Sofridos', category: 'defending', format: 'integer', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['T Desa']) - ctx.pf(r['Des C']) },
    { key: 'driblesS90', label: 'Dribles Sof/90', category: 'defending', format: 'number', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['T Desa']) - ctx.pf(r['Des C']), ctx.j90) },
    { key: 'interceptacoes', label: 'Interceptações', category: 'defending', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Crt']) },
    { key: 'int90', label: 'Int/90', category: 'defending', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Crt']), ctx.j90) },
    { key: 'bloqueios', label: 'Bloqueios', category: 'defending', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Blq']) },
    { key: 'bloq90', label: 'Bloq/90', category: 'defending', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Blq']), ctx.j90) },
    { key: 'remsBloq', label: 'Remates Bloqueados', category: 'defending', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Rems Bloq']) },
    { key: 'remsBloq90', label: 'Rems Bloq/90', category: 'defending', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Rems Bloq']), ctx.j90) },
    { key: 'alivios', label: 'Alívios', category: 'defending', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Alívios']) },
    { key: 'alivios90', label: 'Alívios/90', category: 'defending', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Alívios']), ctx.j90) },
    { key: 'crtD', label: 'Cortes Decisivos', category: 'defending', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Crt D']) },
    { key: 'crtD90', label: 'Crt D/90', category: 'defending', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Crt D']), ctx.j90) },

    // ── PRESSING ──
    { key: 'pressaoT', label: 'Pressão Tentada', category: 'pressing', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Press. tent.']) },
    { key: 'pressaoT90', label: 'Pressão T/90', category: 'pressing', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Press. tent.']), ctx.j90) },
    { key: 'pressaoG', label: 'Pressão Ganha', category: 'pressing', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Press. conc.']) },
    { key: 'pressaoG90', label: 'Pressão G/90', category: 'pressing', format: 'number', displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Press. conc.']), ctx.j90) },
    { key: 'pctPressao', label: '% Pressão', category: 'pressing', format: 'percentage', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Press. conc.']), ctx.pf(r['Press. tent.'])) },
    { key: 'possGanha90', label: 'Posse Ganha/90', category: 'pressing', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Poss Con/90']) },
    { key: 'possPerd90', label: 'Posse Perdida/90', category: 'pressing', format: 'number', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['Poss Perd/90']) },

    // ── PASSING ──
    { key: 'passesT', label: 'Passes Tentados', category: 'passing', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Pas A']) },
    { key: 'passesT90', label: 'Passes T/90', category: 'passing', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Pas A']), ctx.j90) },
    { key: 'passesC', label: 'Passes Certos', category: 'passing', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Ps C']) },
    { key: 'passesC90', label: 'Passes C/90', category: 'passing', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Ps C']), ctx.j90) },
    { key: 'pctPassesCertos', label: '% Passes Certos', category: 'passing', format: 'percentage', displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Ps C']), ctx.pf(r['Pas A'])) },
    { key: 'passesErr', label: 'Passes Errados', category: 'passing', format: 'integer', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['Pas A']) - ctx.pf(r['Ps C']) },
    { key: 'passesErr90', label: 'Passes Err/90', category: 'passing', format: 'number', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Pas A']) - ctx.pf(r['Ps C']), ctx.j90) },
    { key: 'passesProgr', label: 'Passes Progressão', category: 'passing', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['PeP']) },
    { key: 'passesProgr90', label: 'Pass Prog/90', category: 'passing', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['PeP']), ctx.j90) },

    // ── DRIBBLING ──
    { key: 'fintas', label: 'Fintas', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Fnt']) },
    { key: 'fintas90', label: 'Fintas/90', category: 'attacking', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Fnt']), ctx.j90) },

    // ── DISCIPLINE ──
    { key: 'amarelos', label: 'Amarelos', category: 'discipline', format: 'integer', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['Amr']) },
    { key: 'vermelhos', label: 'Vermelhos', category: 'discipline', format: 'integer', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['Cartões vermelhos']) },
    { key: 'totalCartoes', label: 'Total Cartões', category: 'discipline', format: 'integer', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['Amr']) + ctx.pf(r['Cartões vermelhos']) },
    { key: 'faltasComet', label: 'Faltas Cometidas', category: 'discipline', format: 'integer', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['Faltas Cometidas']) },
    { key: 'faltas90', label: 'Faltas/90', category: 'discipline', format: 'number', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Faltas Cometidas']), ctx.j90) },
    { key: 'errosGol', label: 'Erros → Gol', category: 'discipline', format: 'integer', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['EPG']) },
    { key: 'erros90', label: 'Erros/90', category: 'discipline', format: 'number', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['EPG']), ctx.j90) },

    // ── PHYSICAL ──
    { key: 'distancia', label: 'Distância', category: 'physical', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Distância']) },
    { key: 'dist90', label: 'Dist/90', category: 'physical', format: 'number', displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Distância']), ctx.j90) },
    { key: 'sprints90', label: 'Sprints/90', category: 'physical', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Sprints/90']) },

    // ── OFFENSIVE PLAYS ──
    { key: 'lancesOfT', label: 'Lances Of. Tentados', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Remates']) + ctx.pf(r['Passes Ch']) + ctx.pf(r['Fnt']) + ctx.pf(r['Cr T']) },
    { key: 'lancesOf90', label: 'Lances Of/90', category: 'attacking', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Remates']) + ctx.pf(r['Passes Ch']) + ctx.pf(r['Fnt']) + ctx.pf(r['Cr T']), ctx.j90) },
    { key: 'lancesOfC', label: 'Lances Of. Conseguidos', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Rem %']) + ctx.pf(r['Assist.']) + ctx.pf(r['Cr C']) },
    { key: 'lancesOfC90', label: 'Lances Of C/90', category: 'attacking', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Rem %']) + ctx.pf(r['Assist.']) + ctx.pf(r['Cr C']), ctx.j90) },

    // ── CREATION ADVANCED ──
    { key: 'acoesFinalizacao', label: 'Ações de Finalização', category: 'shooting', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Remates']) + ctx.pf(r['Cabs']) },
    { key: 'acoesFinalizacao90', label: 'Ações Fin/90', category: 'shooting', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Remates']) + ctx.pf(r['Cabs']), ctx.j90) },
    { key: 'chancesCriadas', label: 'Chances Criadas', category: 'creation', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Passes Ch']) + ctx.pf(r['OCG']) },
    { key: 'chances90', label: 'Chances/90', category: 'creation', format: 'number', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Passes Ch']) + ctx.pf(r['OCG']), ctx.j90) },

    // ── PENALTIES ──
    { key: 'pensBatidos', label: 'Pênaltis Batidos', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Pens']) },
    { key: 'pensMarcados', label: 'Pênaltis Marcados', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Pens M']) },
    { key: 'pensPerdidos', label: 'Pênaltis Perdidos', category: 'attacking', format: 'integer', displayInTable: false, lowerIsBetter: true,
      formula: (r, ctx) => ctx.pf(r['Pens']) - ctx.pf(r['Pens M']) },
    { key: 'pctPen', label: '% Conv. Pênalti', category: 'attacking', format: 'percentage', displayInTable: false, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Pens M']), ctx.pf(r['Pens'])) },

    // ── NOTA ──
    { key: 'notaMedia', label: 'Nota Média', category: 'general', format: 'number', decimals: 2, displayInTable: true, lowerIsBetter: false,
      formula: (r, ctx) => ctx.pf(r['Classificação']) },
  ],
}
