import type { PositionConfig } from './types.ts'

export const timeConfig: PositionConfig = {
  key: 'time',
  emoji: '📊',
  name: 'Time Estatísticas',

  rawColumns: [
    'Inf', 'Escolhido', 'Jogador', 'Idade', 'Altura', 'Pé Preferido',
    'Minutos', 'Classificação', 'Golos', 'Assist.', 'Pens', 'Pens M',
    'Remates', 'Rem %', 'Cab A', 'Cabs', 'xG', 'xA', 'Poss Perd/90',
    'OCG', 'Passes Ch', 'Cr T', 'Cr C', 'CT-JA', 'CC-JA', 'Crt D',
    'Faltas Cometidas', 'Faltas Contra', 'EPG', 'Distância', 'Fnt',
    'Pas A', 'Ps C', 'PeP', 'Press. tent.', 'Press. conc.',
    'T Desa', 'Des C',
  ],

  identityColumns: {
    Jogador: 'Jogador',
    Idade: 'Idade',
  },

  metrics: [
    // ── general ──────────────────────────────────────────────
    {
      key: 'minutosJogados',
      label: 'Minutos Jogados',
      category: 'general',
      formula: (r, ctx) => ctx.pf(r['Minutos']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'jogosCompletos',
      label: 'Jogos completos',
      category: 'general',
      formula: (_r, ctx) => ctx.j90,
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 1,
    },
    {
      key: 'altura',
      label: 'Altura',
      category: 'general',
      formula: (r, ctx) => {
        const raw = ctx.pf(r['Altura'])
        // FM exports height in cm (e.g. 183); convert to m
        return raw > 3 ? ctx.rnd(raw / 100) : ctx.rnd(raw)
      },
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
      description: 'Altura em metros (converte de cm se necessário)',
    },
    // ── passing ──────────────────────────────────────────────
    {
      key: 'passesT90',
      label: 'Passes T/90',
      category: 'passing',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Pas A']), ctx.j90),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'passesC90',
      label: 'Pass C/90',
      category: 'passing',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Ps C']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'passesErrados90',
      label: 'Passes Errados/90',
      category: 'passing',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Pas A']) - ctx.pf(r['Ps C']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: true,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'pctPassesCertos',
      label: '% Passes Certos',
      category: 'passing',
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Ps C']), ctx.pf(r['Pas A'])),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'percentage',
      decimals: 1,
    },
    {
      key: 'passesTentados',
      label: 'Passes Tentados',
      category: 'passing',
      formula: (r, ctx) => ctx.pf(r['Pas A']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'passesErrados',
      label: 'Passes Errados',
      category: 'passing',
      formula: (r, ctx) => ctx.pf(r['Pas A']) - ctx.pf(r['Ps C']),
      displayInTable: false,
      lowerIsBetter: true,
      format: 'integer',
    },
    {
      key: 'pctPassesErrados',
      label: '% Passes Errados',
      category: 'passing',
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Pas A']) - ctx.pf(r['Ps C']), ctx.pf(r['Pas A'])),
      displayInTable: false,
      lowerIsBetter: true,
      format: 'percentage',
      decimals: 1,
    },
    {
      key: 'possePerdida',
      label: 'Posse Perdida',
      category: 'passing',
      formula: (r, ctx) => ctx.rnd(ctx.pf(r['Poss Perd/90']) * ctx.j90),
      displayInTable: false,
      lowerIsBetter: true,
      format: 'number',
      decimals: 1,
    },
    {
      key: 'possePerdida90',
      label: 'Posse Perdida/90',
      category: 'passing',
      formula: (r, ctx) => ctx.pf(r['Poss Perd/90']),
      displayInTable: false,
      lowerIsBetter: true,
      format: 'number',
      decimals: 2,
    },
    // ── discipline ───────────────────────────────────────────
    {
      key: 'falhas',
      label: 'Falhas',
      category: 'discipline',
      formula: (r, ctx) => ctx.pf(r['EPG']),
      displayInTable: false,
      lowerIsBetter: true,
      format: 'integer',
    },
    {
      key: 'falhas90',
      label: 'Falhas/90',
      category: 'discipline',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['EPG']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: true,
      format: 'number',
      decimals: 2,
    },
    // ── attacking ────────────────────────────────────────────
    {
      key: 'acoesBola',
      label: 'Ações com Bola',
      category: 'attacking',
      formula: (r, ctx) =>
        ctx.pf(r['Cr T']) + ctx.pf(r['Remates']) + ctx.pf(r['Fnt']) + ctx.pf(r['Minutos']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'acoesBola90',
      label: 'Ações Bola/90',
      category: 'attacking',
      formula: (r, ctx) => {
        const total = ctx.pf(r['Cr T']) + ctx.pf(r['Remates']) + ctx.pf(r['Fnt']) + ctx.pf(r['Minutos'])
        return ctx.sDiv(total, ctx.j90)
      },
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'gols',
      label: 'Gols',
      category: 'attacking',
      formula: (r, ctx) => ctx.pf(r['Golos']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'gols90',
      label: 'Gols/90',
      category: 'attacking',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Golos']), ctx.j90),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'golsAst',
      label: 'Gols + Ast',
      category: 'attacking',
      formula: (r, ctx) => ctx.pf(r['Golos']) + ctx.pf(r['Assist.']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'golsAst90',
      label: 'G+A/90',
      category: 'attacking',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Golos']) + ctx.pf(r['Assist.']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'fintas',
      label: 'Fintas',
      category: 'attacking',
      formula: (r, ctx) => ctx.pf(r['Fnt']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'fintas90',
      label: 'Fintas/90',
      category: 'attacking',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Fnt']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    // ── shooting ─────────────────────────────────────────────
    {
      key: 'acoesFinalizacao',
      label: 'Ações Finalização',
      category: 'shooting',
      formula: (r, ctx) =>
        ctx.pf(r['Rem %']) + ctx.pf(r['xA']) + ctx.pf(r['Remates']) + ctx.pf(r['Golos']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 1,
    },
    {
      key: 'acoesFin90',
      label: 'Ações Fin/90',
      category: 'shooting',
      formula: (r, ctx) => {
        const total = ctx.pf(r['Rem %']) + ctx.pf(r['xA']) + ctx.pf(r['Remates']) + ctx.pf(r['Golos'])
        return ctx.sDiv(total, ctx.j90)
      },
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'xgSemPen',
      label: 'xG sem Pen',
      category: 'shooting',
      formula: (r, ctx) => ctx.rnd(ctx.pf(r['xG']) - ctx.pf(r['Pens']) * 0.79),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'npxg90',
      label: 'npxG/90',
      category: 'shooting',
      formula: (r, ctx) => {
        const npxg = ctx.pf(r['xG']) - ctx.pf(r['Pens']) * 0.79
        return ctx.sDiv(npxg, ctx.j90)
      },
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'finalizacoes',
      label: 'Finalizações',
      category: 'shooting',
      formula: (r, ctx) => ctx.pf(r['Remates']) - ctx.pf(r['Pens']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'fin90',
      label: 'Fin/90',
      category: 'shooting',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Remates']) - ctx.pf(r['Pens']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'finCertas90',
      label: 'Fin Certas/90',
      category: 'shooting',
      formula: (r, ctx) =>
        ctx.sDiv(ctx.pf(r['Rem %']) - ctx.pf(r['Pens M']), ctx.j90 - ctx.pf(r['Pens'])),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'pctFinCertas',
      label: '% Fin Certas',
      category: 'shooting',
      formula: (r, ctx) =>
        ctx.pct(ctx.pf(r['Rem %']) - ctx.pf(r['Pens M']), ctx.pf(r['Remates']) - ctx.pf(r['Pens'])),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'percentage',
      decimals: 1,
    },
    {
      key: 'conversaoGols',
      label: 'Conversão Gols',
      category: 'shooting',
      formula: (r, ctx) =>
        ctx.pct(ctx.pf(r['Golos']) - ctx.pf(r['Pens M']), ctx.pf(r['Remates']) - ctx.pf(r['Pens'])),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'percentage',
      decimals: 1,
    },
    // ── creation ─────────────────────────────────────────────
    {
      key: 'cruzamentos',
      label: 'Cruzamentos',
      category: 'creation',
      formula: (r, ctx) => ctx.pf(r['Cr T']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'cruzConseguidos',
      label: 'Cruz Conseguidos',
      category: 'creation',
      formula: (r, ctx) => ctx.pf(r['Cr C']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'pctCruzamentos',
      label: '% Cruzamentos',
      category: 'creation',
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Cr C']), ctx.pf(r['Cr T'])),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'percentage',
      decimals: 1,
    },
    {
      key: 'xA',
      label: 'xA',
      category: 'creation',
      formula: (r, ctx) => ctx.pf(r['xA']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'xA90',
      label: 'xA/90',
      category: 'creation',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['xA']), ctx.j90),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'xAxgSemPen',
      label: 'xA + xG sem Pen',
      category: 'creation',
      formula: (r, ctx) => {
        const xA = ctx.pf(r['xA'])
        const npxg = ctx.pf(r['xG']) - ctx.pf(r['Pens']) * 0.79
        return ctx.rnd(xA + npxg)
      },
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'xAxg90',
      label: 'xA + xG/90',
      category: 'creation',
      formula: (r, ctx) => {
        const xA = ctx.pf(r['xA'])
        const npxg = ctx.pf(r['xG']) - ctx.pf(r['Pens']) * 0.79
        return ctx.sDiv(xA + npxg, ctx.j90)
      },
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'assistencias',
      label: 'Assistências',
      category: 'creation',
      formula: (r, ctx) => ctx.pf(r['Assist.']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'ast90',
      label: 'Ast/90',
      category: 'creation',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Assist.']), ctx.j90),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'passesDecisivos',
      label: 'Passes Decisivos',
      category: 'creation',
      formula: (r, ctx) => ctx.pf(r['Passes Ch']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'passD90',
      label: 'Pass D/90',
      category: 'creation',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Passes Ch']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    // ── aerial ───────────────────────────────────────────────
    {
      key: 'cabsDisputados',
      label: 'Cabeceios Disputados',
      category: 'aerial',
      formula: (r, ctx) => ctx.pf(r['Cabs']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'cabsDisp90',
      label: 'Cabs Disp/90',
      category: 'aerial',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Cabs']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'cabsGanhos',
      label: 'Cabeceios Ganhos',
      category: 'aerial',
      formula: (r, ctx) => ctx.pf(r['Cab A']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'cabsG90',
      label: 'Cabs G/90',
      category: 'aerial',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Cab A']), ctx.j90),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'pctCabs',
      label: '% Cabs',
      category: 'aerial',
      formula: (r, ctx) => ctx.pct(ctx.pf(r['Cab A']), ctx.pf(r['Cabs'])),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'percentage',
      decimals: 1,
    },
    // ── defending ────────────────────────────────────────────
    {
      key: 'desarmesTentados',
      label: 'Desarmes Tentados',
      category: 'defending',
      formula: (r, ctx) => ctx.pf(r['T Desa']) + ctx.pf(r['Faltas Cometidas']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'desT90',
      label: 'Des T/90',
      category: 'defending',
      formula: (r, ctx) =>
        ctx.sDiv(ctx.pf(r['T Desa']) + ctx.pf(r['Faltas Cometidas']), ctx.j90),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'desG90',
      label: 'Des G/90',
      category: 'defending',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Des C']), ctx.j90),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    {
      key: 'pctDesarmes',
      label: '% Desarmes',
      category: 'defending',
      formula: (r, ctx) =>
        ctx.pct(ctx.pf(r['Des C']), ctx.pf(r['T Desa']) + ctx.pf(r['Faltas Cometidas'])),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'percentage',
      decimals: 1,
    },
    // ── discipline (fouls) ───────────────────────────────────
    {
      key: 'faltasCometidas',
      label: 'Faltas cometidas',
      category: 'discipline',
      formula: (r, ctx) => ctx.pf(r['Faltas Cometidas']),
      displayInTable: false,
      lowerIsBetter: true,
      format: 'integer',
    },
    {
      key: 'faltas90',
      label: 'Faltas/90',
      category: 'discipline',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Faltas Cometidas']), ctx.j90),
      displayInTable: true,
      lowerIsBetter: true,
      format: 'number',
      decimals: 2,
    },
    // ── setpiece ─────────────────────────────────────────────
    {
      key: 'chancesBPTentadas',
      label: 'Chances BP Tentadas',
      category: 'setpiece',
      formula: (r, ctx) => ctx.pf(r['CT-JA']) - ctx.pf(r['Cr T']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'chancesBPCriadas',
      label: 'Chances BP Criadas',
      category: 'setpiece',
      formula: (r, ctx) => ctx.pf(r['CC-JA']) - ctx.pf(r['Cr C']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'integer',
    },
    {
      key: 'pctAprovBP',
      label: '% Aproveitamento BP',
      category: 'setpiece',
      formula: (r, ctx) => {
        const tentadas = ctx.pf(r['CT-JA']) - ctx.pf(r['Cr T'])
        const criadas = ctx.pf(r['CC-JA']) - ctx.pf(r['Cr C'])
        return ctx.pct(criadas, tentadas)
      },
      displayInTable: false,
      lowerIsBetter: false,
      format: 'percentage',
      decimals: 1,
    },
    // ── physical ─────────────────────────────────────────────
    {
      key: 'distancia',
      label: 'Distância',
      category: 'physical',
      formula: (r, ctx) => ctx.pf(r['Distância']),
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 1,
    },
    {
      key: 'dist90',
      label: 'Dist/90',
      category: 'physical',
      formula: (r, ctx) => ctx.sDiv(ctx.pf(r['Distância']), ctx.j90),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    // ── general (nota) ───────────────────────────────────────
    {
      key: 'notaMedia',
      label: 'Nota Média',
      category: 'general',
      formula: (r, ctx) => ctx.pf(r['Classificação']),
      displayInTable: true,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
    },
    // ── Moneyball Score (planilha original) ────────────────────
    {
      key: '_moneyball',
      label: 'Moneyball Score',
      category: 'general',
      formula: (r, ctx) => {
        const { pf, clamp, rnd } = ctx
        return clamp(rnd(pf(r['Classificação']) * 10), 0, 100)
      },
      displayInTable: false,
      lowerIsBetter: false,
      format: 'number',
      decimals: 2,
      description: 'Score da planilha original (Nota FM x 10)',
    },
  ],

  defaultTableColumns: [
    'jogosCompletos',
    'passesT90',
    'pctPassesCertos',
    'xA90',
    'npxg90',
    'gols90',
    'ast90',
    'cabsG90',
    'desG90',
    'faltas90',
    'dist90',
    'notaMedia',
  ],
}
