import { describe, expect, it } from 'vitest'
import { derivePlayer } from '@/engine/derive.ts'
import type { RawPlayer } from '@/types/player.ts'
import { overallConfig } from '../overall.ts'

const RAW_COLUMNS = [
  'Inf', 'Nação', 'Jogador', 'Idade', 'Clube', 'Altura', 'Pé Preferido',
  'Valor Estimado', 'Salário', 'Expira', 'Minutos', 'Presenças', 'HdJ',
  'Golos', 'Assist.', 'Golos DS', 'OCG', 'Poss Con/90', 'Poss Perd/90',
  'xG', 'xA', 'Faltas Cometidas', 'Faltas Contra', 'Pas A', 'Ps C',
  'Passes Ch', 'PeP', 'Fnt', 'Remates', 'Rem %', 'Cab A', 'Cabs',
  'Press. tent.', 'Press. conc.', 'T Desa', 'Des C', 'Crt',
  'CT-JA', 'CC-JA', 'Cr T', 'Cr C',
  'Golos marcados de fora da área', 'Remates de fora da área em cada 90 minutes',
  'Remates em livres', 'Fj', 'Blq', 'Rems Bloq', 'Alívios', 'Crt D',
  'Amr', 'Cartões vermelhos', 'EPG', 'Sprints/90',
  'Pens', 'Pens M', 'Distância', 'Classificação',
]

const DERIVED_LABELS = [
  'Jogos completos',
  'Jogos Totais',
  'Minutos por partida',
  'Jogos como Titular',
  'Man of the match',
  'Minutos pra ser o homem do jogo',
  '% de vezes que foi eleito o Homem do Jogo',
  'Gols',
  'Assistências',
  'Gols + Assist',
  'Gols/90',
  'Assistência /90',
  'Gols + A/90',
  'xG',
  'xG sem pênalti',
  'non Pen xG/90',
  'Assistências Esperadas xA',
  'xA /90',
  'xG + xA',
  'xG + xA /90',
  'Finalizações (Total)',
  'Finalizações /90',
  'Finalizações no gol',
  'Finalizações no gol /90',
  '% Finalizações em direção ao gol',
  'Finalizações pra marcar um gol',
  'Finalizações no gol pra marcar um gol',
  '% Finalizações que converteram em gol',
  'Minutos pra tentar uma finalização',
  'Minutos pra acertar um remate no gol',
  'Minutos pra MARCAR um gol',
  'Minutos pra PARTICIPAR de um gol',
  'Gols não esperados',
  'Gols não esperados SEM PÊNALTI',
  'Fora de jogo',
  'Fora de jogo/90',
  'Cabeceios Disputados',
  'Cabeceios Ganhos',
  'Cabeceios Perdidos',
  'Cabeceios Ganhos/90',
  '% Cabs',
  'Desarmes Tentados',
  'Desarmes Ganhos',
  'Dribles Sofridos',
  'Des Ganhos/90',
  'Dribles Sofridos/90',
  '%Des Ganhos',
  'Faltas cometidas',
  'Faltas/90',
  'Cartões Amarelos',
  'Cartão Amarelo/90',
  'Cartão Vermelho',
  'Cartão Vermelho/90',
  'Cartões Recebidos no Total',
  '% Cartões por falta cometida',
  'Proporção de posse Ganha - Perdida',
  'Movimentos de pressão Tentados',
  'Movimentos de pressão Concretizados',
  '% Pressão pra roubar a bola com sucesso',
  'Lances disputados',
  'Lances disputados/90',
  'Lances ganhos',
  'Lances ganhos/90',
  '% Lances disputados e ganhos de forma limpa',
  'Bolas Interceptadas',
  'Bolas Int / 90',
  'Bolas roubadas',
  'Bolas roubadas / 90',
  'Tentativas de  Criar  uma chance em Bola Parada',
  'Tentativas/90',
  'Chances Criadas em Bola Parada',
  'Chances C /90',
  '% Aproveitamento das Tentativas de Criar chance em  BP',
  'Pênaltis batidos',
  'Pênaltis marcados',
  'Pênaltis perdidos',
  '% Conversão de pênalti',
  'Lances ofensivos Tentados',
  'Lances ofensivos tentados/90',
  'Lances OF conseguidos',
  'Lances OF conseguidos/90',
  '% Lances ofensivos conseguidos',
  'Lances defensivos Tentados',
  'Lances defensivos tentados/90',
  'Lances DEF conseguidos',
  'Lances DEF conseguidos/90',
  '% Lances defensivos conseguidos',
  'Lances Tentados (Ataque e Defesa)',
  'Lances Conseguidos (ATA e DEF)',
  '% Acertos Global',
  'Fintas',
  'Fintas/90',
  'Jogadas de Criação',
  'Criação/90',
  'Tentativas de marcar um gol',
  'Tentativas de marcar um gol/90',
  'Tentativas totais de remate de fora da área',
  'Tentativas de Remates de fora da área /90',
  'Participações do jogador',
  'Participações do jogador /90',
  'Ações no último terço',
  'Ações que geraram finalizações ao gol',
  'Ações que geraram finalizações ao gol /90',
  'Passes Decisivos',
  'Pass D /90',
  'Passes Decisivos pra uma assistência',
  'Pass Decisivos que se converteram em assistências',
  'Assistências Claras que a Equipe desperdiçou',
  'xA / Passe Decisivo',
  'Ações com Bola',
  'Ações com Bola/90',
  'Minutos pra fazer um Passe Decisivo',
  'Minutos pra criar uma chance perigosa',
  'Passes Tentados /90',
  'Passes Completados /90',
  '% Passes',
  'Distância percorrida',
  'Distância percorrida/90',
  'Velocidade Média (em km/h)',
  'Sprints de alta intensidade',
  'Sprints/90',
  'Posse Desperdiçada',
  'Posse Desperdiçada /90',
  'Posse Perdida/90',
  'Pontuação recebida',
  'Nota média',
]

const SHEET_METRIC_KEYS = [
  'jogosCompletos', 'jogosTotais', 'minPartida', 'jogosComoTitular',
  'hdj', 'minHdj', 'pctHdj', 'gols', 'assist', 'golsAst', 'gols90',
  'ast90', 'golsAst90', 'xG', 'npxG', 'npxG90', 'xA', 'xA90',
  'xGxA', 'xGxA90', 'finalizacoes', 'fin90', 'finNoGol', 'finNoGol90',
  'pctFinNoGol', 'finPorGol', 'finNoGolPorGol', 'conversaoGols',
  'minPorFinalizacao', 'minPorFinNoGol', 'minPorGol',
  'minPorParticipacaoGol', 'golsNaoEsperados', 'golsNaoEspSemPen',
  'foraJogo', 'foraJogo90', 'cabsDisp', 'cabsG', 'cabsPerd', 'cabsG90',
  'pctCabs', 'desT', 'desG', 'driblesS', 'desG90', 'driblesS90',
  'pctDes', 'faltasComet', 'faltas90', 'amarelos', 'amarelos90',
  'vermelhos', 'vermelhos90', 'totalCartoes', 'cartoesPorFalta',
  'saldoPosse', 'pressaoT', 'pressaoG', 'pctPressao', 'lancesDisputados',
  'lancesDisputados90', 'lancesGanhos', 'lancesGanhos90',
  'pctLancesGanhos', 'bolasInt', 'bolasInt90', 'bolasRoubadas',
  'bolasRoubadas90', 'tentsBP', 'tentsBP90', 'chancesBP', 'chancesBP90',
  'pctBP', 'pensBatidos', 'pensMarcados', 'pensPerdidos', 'pctPen',
  'lancesOfT', 'lancesOf90', 'lancesOfC', 'lancesOfC90', 'pctLancesOf',
  'lancesDefT', 'lancesDefT90', 'lancesDefC', 'lancesDefC90',
  'pctLancesDef', 'lancesTotais', 'lancesConseguidosGlobal',
  'pctAcertoGlobal', 'fintas', 'fintas90', 'jogadasCriacao',
  'jogadasCriacao90', 'tentativasGol', 'tentativasGol90',
  'rematesForaTotal', 'rematesFora90', 'participacoes', 'participacoes90',
  'acoesUltimoTerco', 'acoesGeraramFin', 'acoesGeraramFin90', 'passD',
  'passD90', 'passDecParaAst', 'passDecConvertidos', 'chancesDespEquipe',
  'xAResult', 'acoesComBola', 'acoesComBola90', 'minPorPassD',
  'minPorChancePerigosa', 'passesT90', 'passesC90', 'pctPassesCertos',
  'distancia', 'dist90', 'velocidadeMedia', 'sprintsTotal', 'sprints90',
  'possDesp', 'possDesp90', 'possPerd90', 'pontuacaoRecebida', 'notaMedia',
]

// Linha 2 da aba 🌎Overall Análise.
const GUSTAVO_HENRIQUE: RawPlayer = {
  Inf: '',
  Nação: 'BRA',
  Jogador: 'Gustavo Henrique',
  Idade: '33',
  Clube: 'Corinthians',
  Altura: '196 cm',
  'Pé Preferido': 'Pé Direito',
  'Valor Estimado': '30m € - 500m €',
  Salário: '159m € p/m',
  Expira: '31/12/2027',
  Minutos: '3624',
  Presenças: '42 (3)',
  HdJ: '2',
  Golos: '0',
  'Assist.': '1',
  'Golos DS': '16',
  OCG: '1',
  'Poss Con/90': '10.3',
  'Poss Perd/90': '4.1',
  xG: '1.4',
  xA: '0.14',
  'Faltas Cometidas': '12',
  'Faltas Contra': '3',
  'Pas A': '1909',
  'Ps C': '1766',
  'Passes Ch': '8',
  PeP: '158',
  Fnt: '2',
  Remates: '20',
  'Rem %': '6',
  'Cab A': '233',
  Cabs: '181',
  'Press. tent.': '84',
  'Press. conc.': '21',
  'T Desa': '19',
  'Des C': '18',
  Crt: '134',
  'CT-JA': '0',
  'CC-JA': '0',
  'Cr T': '0',
  'Cr C': '0',
  'Golos marcados de fora da área': '0',
  'Remates de fora da área em cada 90 minutes': '0',
  'Remates em livres': '0',
  Fj: '0',
  Blq: '27',
  'Rems Bloq': '24',
  Alívios: '55',
  'Crt D': '3',
  Amr: '1',
  'Cartões vermelhos': '1',
  EPG: '0',
  'Sprints/90': '5.5',
  Pens: '0',
  'Pens M': '0',
  Distância: '392,7 km',
  Classificação: '6.85',
}

const GUSTAVO_EXPECTED: Record<string, number> = {
  jogosCompletos: 40.266666666666666,
  jogosTotais: 45,
  minPartida: 80.53,
  jogosComoTitular: 93,
  hdj: 2,
  minHdj: 1812,
  pctHdj: 4.97,
  gols: 0,
  assist: 1,
  golsAst: 1,
  gols90: 0,
  ast90: 0.02,
  golsAst90: 0.02,
  xG: 1.4,
  npxG: 1.4,
  npxG90: 0.03,
  xA: 0.14,
  xA90: 0,
  xGxA: 1.54,
  xGxA90: 0.04,
  finalizacoes: 20,
  fin90: 0.5,
  finNoGol: 6,
  finNoGol90: 0.15,
  pctFinNoGol: 30,
  finPorGol: 50,
  finNoGolPorGol: 50,
  conversaoGols: 0,
  minPorFinalizacao: 181.2,
  minPorFinNoGol: 604,
  minPorGol: 3624,
  minPorParticipacaoGol: 3624,
  golsNaoEsperados: -1.4,
  golsNaoEspSemPen: -1.4,
  foraJogo: 0,
  foraJogo90: 0,
  cabsDisp: 233,
  cabsG: 181,
  cabsPerd: 52,
  cabsG90: 4.5,
  pctCabs: 77.68,
  desT: 31,
  desG: 18,
  driblesS: 1,
  desG90: 0.45,
  driblesS90: 0.02,
  pctDes: 58.06,
  faltasComet: 12,
  faltas90: 0.3,
  amarelos: 1,
  amarelos90: 0.02,
  vermelhos: 1,
  vermelhos90: 0.02,
  totalCartoes: 2,
  cartoesPorFalta: 16.67,
  saldoPosse: 6.2,
  pressaoT: 84,
  pressaoG: 21,
  pctPressao: 25,
  lancesDisputados: 351,
  lancesDisputados90: 8.72,
  lancesGanhos: 223,
  lancesGanhos90: 5.54,
  pctLancesGanhos: 63.53,
  bolasInt: 243,
  bolasInt90: 6.03,
  bolasRoubadas: 43.5,
  bolasRoubadas90: 1.08,
  tentsBP: 0,
  tentsBP90: 0,
  chancesBP: 0,
  chancesBP90: 0,
  pctBP: 0,
  pensBatidos: 0,
  pensMarcados: 0,
  pensPerdidos: 0,
  pctPen: 0.00000001,
  lancesOfT: 31,
  lancesOf90: 0.77,
  lancesOfC: 17,
  lancesOfC90: 0.42,
  pctLancesOf: 54.84,
  lancesDefT: 504,
  lancesDefT90: 12.52,
  lancesDefC: 442,
  lancesDefC90: 10.98,
  pctLancesDef: 87.7,
  lancesTotais: 2444,
  lancesConseguidosGlobal: 2225,
  pctAcertoGlobal: 91.04,
  fintas: 2,
  fintas90: 0.05,
  jogadasCriacao: 9,
  jogadasCriacao90: 0.22,
  tentativasGol: 29,
  tentativasGol90: 0.72,
  rematesForaTotal: 0,
  rematesFora90: 0,
  participacoes: 2340,
  participacoes90: 58.11,
  acoesUltimoTerco: 18.5,
  acoesGeraramFin: 15.64,
  acoesGeraramFin90: 0.39,
  passD: 8,
  passD90: 0.2,
  passDecParaAst: 8,
  passDecConvertidos: 12.5,
  chancesDespEquipe: -0.86,
  xAResult: 0.02,
  acoesComBola: 30,
  acoesComBola90: 0.75,
  minPorPassD: 453,
  minPorChancePerigosa: 700,
  passesT90: 47.41,
  passesC90: 43.86,
  pctPassesCertos: 92.51,
  distancia: 392.7,
  dist90: 9.75,
  velocidadeMedia: 6.501655629139073,
  sprintsTotal: 221.46666666666667,
  sprints90: 5.5,
  possDesp: 209,
  possDesp90: 5.19,
  possPerd90: 4.1,
  pontuacaoRecebida: 275.82666666666665,
  notaMedia: 6.85,
}

const LEGACY_KEYS = [
  'jogosCompletos', 'jogosTotais', 'minPartida', 'jogosComoTitular',
  'hdj', 'minHdj', 'pctHdj', 'gols', 'assist', 'golsAst', 'gols90',
  'ast90', 'golsAst90', 'xG', 'npxG', 'npxG90', 'xA', 'xA90', 'xGxA',
  'xGxA90', 'finalizacoes', 'fin90', 'finNoGol', 'finNoGol90',
  'pctFinNoGol', 'conversaoGols', 'golsNaoEsperados', 'golsNaoEspSemPen',
  'cruzT', 'cruzC', 'pctCruz', 'passD', 'passD90', 'xAResult',
  'chancesDespEquipe', 'tentsBP', 'chancesBP', 'pctBP', 'cabsDisp',
  'cabsDisp90', 'cabsG', 'cabsG90', 'pctCabs', 'desT', 'desT90', 'desG',
  'desG90', 'pctDes', 'driblesS', 'driblesS90', 'interceptacoes', 'int90',
  'bloqueios', 'bloq90', 'remsBloq', 'remsBloq90', 'alivios', 'alivios90',
  'crtD', 'crtD90', 'pressaoT', 'pressaoT90', 'pressaoG', 'pressaoG90',
  'pctPressao', 'possGanha90', 'possPerd90', 'passesT', 'passesT90',
  'passesC', 'passesC90', 'pctPassesCertos', 'passesErr', 'passesErr90',
  'passesProgr', 'passesProgr90', 'fintas', 'fintas90', 'amarelos',
  'vermelhos', 'totalCartoes', 'faltasComet', 'faltas90', 'errosGol',
  'erros90', 'distancia', 'dist90', 'sprints90', 'lancesOfT',
  'lancesOf90', 'lancesOfC', 'lancesOfC90', 'acoesFinalizacao',
  'acoesFinalizacao90', 'chancesCriadas', 'chances90', 'pensBatidos',
  'pensMarcados', 'pensPerdidos', 'pctPen', 'notaMedia',
]

describe('overallConfig — paridade com a aba 🌎Overall Análise', () => {
  it('preserva exatamente os 57 cabeçalhos brutos e as identidades', () => {
    expect(overallConfig.rawColumns).toEqual(RAW_COLUMNS)
    expect(overallConfig.identityColumns).toEqual({
      Jogador: 'Jogador',
      Nação: 'Nação',
      Clube: 'Clube',
      Idade: 'Idade',
      Salário: 'Salário',
      Valor: 'Valor Estimado',
    })
  })

  it('reflete, em ordem, todas as 126 colunas calculadas H:EC', () => {
    expect(overallConfig.metrics.slice(0, DERIVED_LABELS.length).map(({ label }) => label))
      .toEqual(DERIVED_LABELS)
    expect(overallConfig.metrics.slice(0, SHEET_METRIC_KEYS.length).map(({ key }) => key))
      .toEqual(SHEET_METRIC_KEYS)
  })

  it('reproduz todas as fórmulas da linha real Gustavo Henrique', () => {
    const player = derivePlayer(GUSTAVO_HENRIQUE, overallConfig)
    expect(player).not.toBeNull()

    for (const [key, expected] of Object.entries(GUSTAVO_EXPECTED)) {
      expect(player?.[key], key).toBeCloseTo(expected, 10)
    }

    expect(Object.keys(GUSTAVO_EXPECTED)).toEqual(SHEET_METRIC_KEYS)
    expect(player).toMatchObject({
      Jogador: 'Gustavo Henrique',
      Nação: 'BRA',
      Clube: 'Corinthians',
      Idade: 33,
      Salário: '159m € p/m',
      Valor: '30m € - 500m €',
    })
  })

  it('mantém os fallbacks literais da planilha', () => {
    const player = derivePlayer({
      ...GUSTAVO_HENRIQUE,
      Minutos: '90',
      Presenças: '1',
      HdJ: '0',
      Golos: '0',
      'Assist.': '0',
      Remates: '0',
      'Rem %': '0',
      'Passes Ch': '0',
      Pens: '0',
      'Pens M': '0',
      Classificação: '',
    }, overallConfig)

    expect(player).not.toBeNull()
    expect(player).toMatchObject({
      jogosTotais: 1,
      jogosComoTitular: 100,
      minHdj: 5400,
      finPorGol: 50,
      finNoGolPorGol: 50,
      minPorFinalizacao: 700,
      minPorFinNoGol: 700,
      minPorGol: 90,
      minPorParticipacaoGol: 90,
      pctPen: 0.00000001,
      passDecParaAst: 70,
      minPorPassD: 700,
      minPorChancePerigosa: 700,
      notaMedia: 5,
    })
  })

  it('preserva keys existentes, unicidade e defaults válidos', () => {
    const metricKeys = overallConfig.metrics.map(({ key }) => key)
    expect(new Set(metricKeys).size).toBe(metricKeys.length)
    expect(metricKeys).toEqual(expect.arrayContaining(LEGACY_KEYS))
    expect(overallConfig.defaultTableColumns.every((key) => metricKeys.includes(key))).toBe(true)
    expect(new Set(
      overallConfig.metrics.filter(({ displayInTable }) => displayInTable).map(({ key }) => key),
    )).toEqual(new Set(overallConfig.defaultTableColumns))
  })

  it('não inventa um score 0–100: pontuação recebida é nota × jogos completos', () => {
    const player = derivePlayer(GUSTAVO_HENRIQUE, overallConfig)
    expect(player?.pontuacaoRecebida).toBeCloseTo(
      Number(player?.notaMedia) * Number(player?.jogosCompletos),
      10,
    )
  })
})
